baseURL = "https://kumakikai.github.io/"
languageCode = "ja"
title = "KUMAKIKAI"
enableRobotsTXT = true
theme = "PaperMod"
timeZone = "Asia/Tokyo"

[pagination]
  pagerSize = 3

# GitHub Pages向け
canonifyURLs = true
relativeURLs = false

[params]
  description = "KUMAKIKAIの公式サイトです。 ／ Official site for KUMAKIKAI apps."

  # ホーム表示調整
  ShowPostSummary = true
  ShowBreadCrumbs = false
  ShowReadingTime = false

  # カスタムCSS読み込み（トップ区切り線・タイル調整用）
  customCSS = ["css/custom.css"]

  mainSections = ["notes"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2
