#!/usr/bin/env python3
"""Generate Hugo product and company entry points from shared JSON data.

Run `python3 scripts/sync-products.py` after editing data/apps.json,
data/home/<language>.json, or data/corporate/<language>.json. Use --check in CI.
Existing editorial content is never overwritten. Generated pages are not deleted
automatically because their URLs may already be used outside this website.
"""
import argparse
import json
from pathlib import Path
import re
import sys

LANGUAGES = ("ja", "en", "ko", "de", "zh-hant", "fr")
SECTIONS = ("products", "support", "news", "company")
MARKER = "# Generated by scripts/sync-products.py. Edit the shared JSON data instead."


def load(path):
    return json.loads(path.read_text(encoding="utf-8"))


def frontmatter(fields):
    lines = ["---", MARKER]
    lines.extend(f"{key}: {json.dumps(value, ensure_ascii=False)}" for key, value in fields.items())
    return "\n".join(lines + ["---", ""])


def generate(root):
    apps = load(root / "data/apps.json")
    if not isinstance(apps, list) or not apps:
        raise ValueError("data/apps.json must contain a nonempty product list")
    ids = [app["id"] for app in apps]
    if len(set(ids)) != len(ids) or any(not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", value) for value in ids):
        raise ValueError("Product IDs must be unique lowercase URL slugs")
    expected = {}
    for lang in LANGUAGES:
        home = load(root / "data/home" / f"{lang}.json")
        corporate = load(root / "data/corporate" / f"{lang}.json")
        suffix = "" if lang == "ja" else f".{lang}"
        for section in SECTIONS:
            expected[root / "content" / section / f"_index{suffix}.md"] = frontmatter({
                "title": corporate["nav"][section],
                "description": corporate[f"{section}Description"],
                "type": section,
            })
        for app in apps:
            copy = home["apps"][app["id"]]
            expected[root / "content/products" / f"{app['id']}{suffix}.md"] = frontmatter({
                "title": copy["name"],
                "description": copy["description"],
                "type": "product",
                "product_id": app["id"],
            })
    return expected


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report out-of-date pages without writing")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1], help="Repository root")
    args = parser.parse_args()
    try:
        expected = generate(args.root.resolve())
        changed = []
        for path, desired in expected.items():
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current == desired:
                continue
            if current is not None and MARKER not in current:
                raise ValueError(f"Refusing to overwrite editorial content: {path}")
            changed.append(path)
        obsolete = []
        for section in SECTIONS:
            directory = args.root / "content" / section
            for path in directory.glob("*.md"):
                if path.resolve() not in expected and MARKER in path.read_text(encoding="utf-8"):
                    obsolete.append(path)
        if obsolete:
            raise ValueError("Generated pages no longer represented in data. Preserve or alias their public URLs before removing them: " + ", ".join(str(p) for p in obsolete))
        if not args.check:
            for path in changed:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(expected[path], encoding="utf-8")
        result = {
            "ok": not (args.check and changed),
            "mode": "check" if args.check else "sync",
            "pages": len(expected),
            "changed": [str(path.relative_to(args.root.resolve())) for path in changed],
        }
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0 if result["ok"] else 1
    except (KeyError, OSError, TypeError, ValueError) as error:
        print(f"Product page sync failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
